version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: effective_mobile_postgres
    environment:
      POSTGRES_DB: effective_mobile_db
      POSTGRES_USER: effective_mobile_user
      POSTGRES_PASSWORD: effective_mobile_password
    ports:
      - "5432:5432"
    volumes:
      - .data/pg:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U effective_mobile_user -d effective_mobile_db" ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".env:/.env"
    ports:
      - "8080:8080"
